# Generated by Django 5.0.2 on 2024-11-27 15:14

import django.db.models.deletion
import gestor_incidencias.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_incidencias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='est_dano',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descrip_corta', models.TextField()),
                ('nom_img', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tp_asist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descrip_corta', models.TextField()),
                ('nom_img', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tp_dano',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descrip_corta', models.TextField()),
                ('nom_img', models.TextField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to=('Incidencias/', gestor_incidencias.models.camb_nom_arch)),
        ),
        migrations.CreateModel(
            name='pers_asist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('obser', models.TextField(blank=True, null=True)),
                ('longitud', models.FloatField(null=True)),
                ('latitud', models.FloatField(null=True)),
                ('cant_anci', models.FloatField(null=True)),
                ('cant_mujeres', models.FloatField(null=True)),
                ('cant_hombres', models.FloatField(null=True)),
                ('cant_ninos', models.FloatField(null=True)),
                ('img', models.FileField(blank=True, null=True, upload_to=('pers_asist/', gestor_incidencias.models.camb_nom_arch))),
                ('depto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor_incidencias.depto')),
                ('munic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor_incidencias.munic')),
                ('procedencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor_incidencias.procedencia')),
                ('tp_asist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor_incidencias.tp_dano')),
            ],
        ),
        migrations.CreateModel(
            name='danos_ocasionados',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('obser', models.TextField(blank=True, null=True)),
                ('longitud', models.FloatField(null=True)),
                ('latitud', models.FloatField(null=True)),
                ('cant', models.FloatField(null=True)),
                ('img', models.FileField(blank=True, null=True, upload_to=('danos/', gestor_incidencias.models.camb_nom_arch))),
                ('depto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor_incidencias.depto')),
                ('munic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor_incidencias.munic')),
                ('procedencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor_incidencias.procedencia')),
                ('est_dano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor_incidencias.est_dano')),
                ('tp_dano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor_incidencias.tp_dano')),
            ],
        ),
    ]
