# Generated by Django 5.0.2 on 2024-11-29 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_incidencias', '0003_alter_danos_ocasionados_img_alter_incidencia_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pers_asist',
            name='tp_asist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor_incidencias.tp_asist'),
        ),
    ]
