# Generated by Django 5.0.2 on 2025-03-09 15:06

import django.db.models.deletion
import gestor_incidencias.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_incidencias', '0004_alter_pers_asist_tp_asist'),
    ]

    operations = [
        migrations.CreateModel(
            name='cv',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('longitud', models.FloatField(null=True)),
                ('latitud', models.FloatField(null=True)),
                ('nom', models.TextField(blank=True, null=True)),
                ('img', models.FileField(blank=True, null=True, upload_to=gestor_incidencias.models.camb_nom_arch)),
                ('cod_depto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestor_incidencias.depto')),
                ('cod_munic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestor_incidencias.munic')),
                ('procedencia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestor_incidencias.procedencia')),
            ],
        ),
    ]
