# Generated by Django 4.2.7 on 2025-05-02 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_incidencias', '0006_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='munic',
            name='cod_munic',
            field=models.TextField(null=True),
        ),
    ]
