# Generated by Django 4.2.7 on 2025-05-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_incidencias', '0008_area_contactoxcv_cv_carga_electoral_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='carga_electoral',
            field=models.TextField(null=True),
        ),
    ]
