# Generated by Django 4.2.7 on 2025-05-04 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_incidencias', '0009_alter_cv_carga_electoral'),
    ]

    operations = [
        migrations.CreateModel(
            name='estado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descrip_corta', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='cv',
            name='cod_estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestor_incidencias.estado'),
        ),
    ]
